export { AuthModule } from './Auth/mobile/Auth';
export { CybersportModule } from './Cybersport/mobile/Cybersport';
export { DownloadAppModule } from './DownloadApp/mobile/DownloadApp';
export { SlotsModule } from './Slots/mobile/Slots';
export { LineModule } from './Line/mobile/Line';
export { LiveModule } from './Live/mobile/Live';
export { FullEventModule } from './FullEvent/mobile/FullEvent';
export { BasketModule } from './Basket/mobile/Basket';
export { ProfileModule } from './Profile/mobile/Profile';
export { FlatPagesModule } from './FlatPages/mobile/FlatPages';
export { LiveGamesModule } from './LiveGames/mobile/LiveGames';
export { ResultsModule } from './Results/mobile/Results';
// export { TotalizatorModule } from './Totalizator/mobile/Totalizator';
export { RestoreByEmailModule } from './RestoreByEmail/mobile/RestoreByEmail';
export { ContactsModule } from './Contacts/mobile/Contacts';
//export { ViewAllModule } from './ViewAll/mobile/viewAll';
export { BonusesModule } from './Bonuses/mobile/Bonuses';
export { MainModule } from './Main/Main';
export { NotFoundModule } from './NotFound/mobile/NotFound';
// export { Menu } from './Menu/Menu';